complete -c rounded-div -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "u8" -d 'Perform rounded division on two u8 numbers'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "u16" -d 'Perform rounded division on two u16 numbers'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "u32" -d 'Perform rounded division on two u32 numbers'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "u64" -d 'Perform rounded division on two u64 numbers'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "u128" -d 'Perform rounded division on two u128 numbers'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "usize" -d 'Perform rounded division on two usize numbers'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "i8" -d 'Perform rounded division on two i8 numbers'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "i16" -d 'Perform rounded division on two i16 numbers'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "i32" -d 'Perform rounded division on two i32 numbers'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "i64" -d 'Perform rounded division on two i64 numbers'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "i128" -d 'Perform rounded division on two i128 numbers'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "isize" -d 'Perform rounded division on two isize numbers'
complete -c rounded-div -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c rounded-div -n "__fish_seen_subcommand_from u8" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from u8" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_seen_subcommand_from u16" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from u16" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_seen_subcommand_from u32" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from u32" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_seen_subcommand_from u64" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from u64" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_seen_subcommand_from u128" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from u128" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_seen_subcommand_from usize" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from usize" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_seen_subcommand_from i8" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from i8" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_seen_subcommand_from i16" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from i16" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_seen_subcommand_from i32" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from i32" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_seen_subcommand_from i64" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from i64" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_seen_subcommand_from i128" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from i128" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_seen_subcommand_from isize" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from isize" -s V -l version -d 'Prints version information'
complete -c rounded-div -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c rounded-div -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
